/* generated by _tools/make_targets.py --project - do not edit */
/* Empty on purpose: a client project contains the RESULT of inlining
   snippets, not the snippets. Nothing of that kind exists to test. */
window.SNIPPETS = [];
