/* generated by _tools/make_targets.py --project - do not edit */
/* DEMOS is the client's PAGES here, not component demos: the console,
   CDN-failure, mobile and keyboard checks walk this list. */
window.DEMOS = [
"../site/404.html",
"../site/case-study.html",
"../site/contact.html",
"../site/index.html",
"../site/privacy.html",
"../site/service.html",
"../site/work.html"
];

window.REVEAL_TARGETS = [
 {
  "id": "page:404",
  "p": "../site/404.html",
  "sel": "[data-reveal]",
  "cls": "in",
  "mode": "all"
 },
 {
  "id": "page:case-study",
  "p": "../site/case-study.html",
  "sel": "[data-reveal]",
  "cls": "in",
  "mode": "all"
 },
 {
  "id": "page:contact",
  "p": "../site/contact.html",
  "sel": "[data-reveal]",
  "cls": "in",
  "mode": "all"
 },
 {
  "id": "page:index",
  "p": "../site/index.html",
  "sel": "[data-reveal]",
  "cls": "in",
  "mode": "all"
 },
 {
  "id": "page:privacy",
  "p": "../site/privacy.html",
  "sel": "[data-reveal]",
  "cls": "in",
  "mode": "all"
 },
 {
  "id": "page:service",
  "p": "../site/service.html",
  "sel": "[data-reveal]",
  "cls": "in",
  "mode": "all"
 },
 {
  "id": "page:work",
  "p": "../site/work.html",
  "sel": "[data-reveal]",
  "cls": "in",
  "mode": "all"
 }
];
